# Deploy automatically using Gitlab CI to Firebase Hosting service.
# Need the Gitlab environment variable $FIREBASE_TOKEN
# To generate the token: firebase login:ci

image: node:12.13.0-alpine

before_script:
  -

deploy:
  stage: deploy
  only: [master]
  script:
    - npm i -g firebase-tools
    - npm i -g @angular/cli
    - npm i
    - ng build --prod
    - firebase deploy --token $FIREBASE_TOKEN
